/**
 * POPSigner mTLS Account Types
 *
 * Type definitions for the custom Viem Account that delegates
 * signing operations to POPSigner's RPC Gateway via mTLS.
 */

import type { Address, Hex } from 'viem';

/**
 * Configuration for creating a POPSigner-backed Viem Account.
 */
export interface POPSignerConfig {
  /**
   * POPSigner RPC Gateway endpoint URL.
   * Must be an HTTPS URL (e.g., "https://rpc.popsigner.com:8546").
   */
  endpoint: string;

  /**
   * Ethereum address associated with this signer.
   * Must be checksummed (0x-prefixed).
   */
  address: Address;

  /**
   * PEM-encoded client certificate for mTLS authentication.
   * Generated by POPSigner during key setup.
   */
  clientCert: string;

  /**
   * PEM-encoded client private key for mTLS authentication.
   * Must match the client certificate.
   */
  clientKey: string;

  /**
   * Optional PEM-encoded CA certificate for server verification.
   * If not provided, system CA certificates are used.
   */
  caCert?: string;

  /**
   * Optional request timeout in milliseconds.
   * Defaults to 30000 (30 seconds).
   */
  timeout?: number;
}

/**
 * JSON-RPC 2.0 request format for POPSigner.
 */
export interface JSONRPCRequest<T = unknown> {
  jsonrpc: '2.0';
  method: string;
  params: T;
  id: number;
}

/**
 * JSON-RPC 2.0 response format from POPSigner.
 */
export interface JSONRPCResponse<T = unknown> {
  jsonrpc: '2.0';
  result?: T;
  error?: JSONRPCError;
  id: number;
}

/**
 * JSON-RPC 2.0 error object.
 */
export interface JSONRPCError {
  code: number;
  message: string;
  data?: unknown;
}

/**
 * Transaction parameters for eth_signTransaction.
 * Uses hex-encoded strings for numeric values.
 */
export interface TransactionParams {
  from: Address;
  to?: Address;
  gas?: Hex;
  gasPrice?: Hex;
  maxFeePerGas?: Hex;
  maxPriorityFeePerGas?: Hex;
  value?: Hex;
  data?: Hex;
  nonce?: Hex;
  chainId?: Hex;
  type?: Hex;
  accessList?: AccessListItem[];
}

/**
 * EIP-2930 access list item.
 */
export interface AccessListItem {
  address: Address;
  storageKeys: Hex[];
}

/**
 * EIP-712 typed data domain.
 */
export interface TypedDataDomain {
  name?: string;
  version?: string;
  chainId?: number | bigint;
  verifyingContract?: Address;
  salt?: Hex;
}

/**
 * Custom error for POPSigner RPC failures.
 */
export class POPSignerError extends Error {
  public readonly code: number;
  public readonly data?: unknown;

  constructor(message: string, code: number, data?: unknown) {
    super(message);
    this.name = 'POPSignerError';
    this.code = code;
    this.data = data;
  }
}

/**
 * Custom error for mTLS configuration issues.
 */
export class MTLSConfigError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'MTLSConfigError';
  }
}

