// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Auth layout for login/signup pages - 80s CRT terminal aesthetic
func Auth(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"min-h-screen bg-black flex flex-col items-center justify-center px-4 py-12 sm:px-6 lg:px-8 relative overflow-hidden font-mono\"><!-- CRT scanlines overlay --><div class=\"absolute inset-0 pointer-events-none opacity-[0.03]\n\t\t\t            bg-[repeating-linear-gradient(0deg,transparent,transparent_1px,rgba(0,0,0,0.3)_1px,rgba(0,0,0,0.3)_2px)]\"></div><!-- Phosphor glow effects --><div class=\"absolute inset-0 -z-10\"><div class=\"absolute top-1/4 left-1/4 w-96 h-96 bg-[#FFB000]/5 rounded-full blur-3xl\"></div><div class=\"absolute bottom-1/4 right-1/4 w-80 h-80 bg-[#33FF00]/5 rounded-full blur-3xl\"></div></div><!-- Logo --><div class=\"mb-8 text-center relative z-10\"><a href=\"/\" class=\"inline-flex items-center gap-3 group\"><span class=\"text-[#FFB000] text-3xl group-hover:drop-shadow-[0_0_15px_#FFB000] transition-all\">◇</span> <span class=\"text-2xl font-bold text-[#FFB000] uppercase tracking-wider\n\t\t\t\t\t             drop-shadow-[0_0_10px_#FFB000] group-hover:drop-shadow-[0_0_20px_#FFB000] transition-all\">POPSIGNER</span></a><p class=\"mt-3 text-[#666600] text-sm tracking-wide uppercase\">Point-of-Presence Signing Infrastructure</p></div><!-- Auth card --><div class=\"w-full max-w-md relative z-10\"><div class=\"bg-black border border-[#333300] p-8\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div><!-- Footer links --><div class=\"mt-8 text-center text-sm text-[#666600] relative z-10 font-mono uppercase\"><a href=\"/docs\" class=\"hover:text-[#FFB000] transition-colors\">Docs</a> <span class=\"mx-2\">·</span> <a href=\"/privacy\" class=\"hover:text-[#FFB000] transition-colors\">Privacy</a> <span class=\"mx-2\">·</span> <a href=\"/terms\" class=\"hover:text-[#FFB000] transition-colors\">Terms</a></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base(title, false, false).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
